### ISSUE TITLE
Transaction fails all gas credit has been spend

### ISSUE THREAD

**Issue by winedog** [Bytom/bytom#1067]
#### Environment

Windows

#### Problem Description

I'm trying to transfer BTM from my wallet to my gate.io address.  I did a test transfer two days ago of 1 BTM and it worked fine.

Today I'm trying to transfer a larger amount of BTM and I get this error every time

tx rejected: checking result 0: checking output source: checking value source: checking gas input: all gas credit has been spend

The amount of gas credit that is estimated is not very much and I have more than enough BTM in my wallet to cover the amount transferred and the gas credit so I don't know why it says there is a problem with the gas credit?

**Comment by qty236** [comment]
Hi, same issue - no matter I want to transfer 10 or 300 BTM.  Wallet version 1.0.3. OS : windows

**Comment by Vindikkator** [comment]
Hi Windog, I had the same problem when trying to transfer 900 BTM.

However I reduced it to 10 and 100 and that when through fine with all the same details and Standard Gas.

Not sure what the issue is with larger transactions I even up the transaction fee several times the Fast option still doesnt work. Maybe a security feature that needs to be tweaked somewhere else in the walled

**Comment by Paladz** [comment]
The root cause of this problem is you can use only 21(might change base on different smart contract) BTM's UTXO in a single transaction.

1. The easy way to fix it is try sent BTM to your own address for merge the UTXOs.
2. We have tools that can help you do this: https://github.com/Bytom/bytom-spanner
3. Download the V1.0.4 version, we optimized the UTXO select algorithm.
