### ISSUE TITLE
 cannot find package "github.com/bytom/cmd/bytomd/commands

### ISSUE THREAD

**Issue by 260235538** [Bytom/bytom#1410]
centos7 install:
root@btm /home/centos]#  cd $GOPATH/src/github.com/bytom
[root@btm /src/github.com/bytom]# make bytomd
Building bytomd to cmd/bytomd/bytomd
cmd/bytomd/main.go:12:2: cannot find package "github.com/bytom/cmd/bytomd/commands" in any of:
	/usr/lib/golang/src/github.com/bytom/cmd/bytomd/commands (from $GOROOT)
	/root/go/src/github.com/bytom/cmd/bytomd/commands (from $GOPATH)
cmd/bytomd/main.go:13:2: cannot find package "github.com/bytom/config" in any of:
	/usr/lib/golang/src/github.com/bytom/config (from $GOROOT)
	/root/go/src/github.com/bytom/config (from $GOPATH)
cmd/bytomd/main.go:9:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/lib/golang/src/github.com/sirupsen/logrus (from $GOROOT)
	/root/go/src/github.com/sirupsen/logrus (from $GOPATH)
cmd/bytomd/main.go:10:2: cannot find package "github.com/tendermint/tmlibs/cli" in any of:
	/usr/lib/golang/src/github.com/tendermint/tmlibs/cli (from $GOROOT)
	/root/go/src/github.com/tendermint/tmlibs/cli (from $GOPATH)

**Comment by Agouri** [comment]
The `$GOPATH` environmental variable isn't set by default, and yours seems to be unset (because your `cd $GOPATH/src/github.com/bytom` just leads you to `/src/github.com/bytom`. To check if your `$GOPATH` is set, just do `echo $GOPATH` in a bash terminal.

If it's not `/home/[your_username]/go`, to solve your problem either
* use `/home/[your_username]/go/src/github.com/bytom` to navigate to your cloned directory of BYTOM, or
* google how to set environmental variables on your CentOS, and declare a permanent entry for `$GOPATH`.

Hope I helped <3

**Comment by HAOYUatHZ** [comment]
@Agouri is right
