### ISSUE TITLE
[外部测试] `make release-all` fails on Mac

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#597]
#### Environment

- OS: OSX

#### Problem Description

On Mac OSX, run

```
make release-all
```

It will show:

```
/bin/sh: md5sum: command not found
make[1]: *** [release] Error 127
make: *** [release-all] Error 2
```

The reason is `md5sum` is not installed on Mac by default, although there is a `md5` command and the output of `md5 -r` is identical to `md5sum`, but I think it's better to mention how to fix it for developers in somewhere:

```
brew install md5sha1sum
```

**Comment by zcc0721** [comment]
You're right. The error can be fixed using:
```
brew install md5sha1sum
```

**Comment by Jasonfloy** [comment]
woow  great job！

**Comment by HAOYUatHZ** [comment]
The reason we prefer `md5sum` rather than `md5 -r` is for cross-platform reason, so the  makefile works for both linux and darwin.

We r going to keep using `md5sum`.

And since at the moment `make release-all` is not targeting users but only serving for our dev team, there is no need to provide this hint.

but yep i have to admit that we'd better mention it somewhere to help with other developer interested in this project. maybe in the wiki for developers

**Comment by HAOYUatHZ** [comment]
@freewind contact our support team via wechat and show them this page to claim ur reward. Thx for ur work!
