### ISSUE TITLE
Cannot Withdraw - Unknown Address

### ISSUE THREAD

**Issue by eusvolk93** [Bytom/bytom#916]
I am trying to withdraw BTM from core wallet. Every time I try to withdraw to an exchange site whether HitBTC or Cryptopia the core wallet says the receiving address is unknown. Anyone have a fix to this issue?

**Comment by unhkd** [comment]
@eusvolk93 you can't, not until they convert to bm addresses(the exchanges). since the exchanges all use erc20 addresses, they start with 0x. The tokens you have in the core wallet are on the new mainnet. It just went live 13 days ago. The exchanges will start to convert erc20 tokens to the new btm over the next month. So for now you can only transfer your non erc20 btm to another desktop wallet. or any address on the mainnet(starts bm)
